version: '1.0'

services:
  service1:
    build:
      context: ./service1
    ports:
      - "3001:3000"
    networks:
      - microservices-net

  service2:
    build:
      context: ./service2
    ports:
      - "3002:3000"
    networks:
      - microservices-net

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service1
      - service2
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge