# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Print Working Directory
        run: pwd

      - name: List Files in Root
        run: ls -la

      - name: Build Docker Image for Service 1
        run: docker build ./service1 --file ./service1/Dockerfile --tag service1:$(date +%s)

      - name: Build Docker Image for Service 2
        run: docker build ./service2 --file ./service2/Dockerfile --tag service2:$(date +%s)

      - name: Build Docker Image for API Gateway
        run: docker build ./api-gateway --file ./api-gateway/Dockerfile --tag api-gateway:$(date +%s)
